name: deploy
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Install project
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Run linter
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: Install project
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm run test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Install project
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deployment
              run: echo "Deploying..."
